### ISSUE TITLE
Updated vcsUrl not refelcted on gradle plugin page

### ISSUE THREAD

**Issue by mattbond** [gradle/plugin-portal-requests#209] opened 2024-01-11 07:46 UTC
We published a new version of our plugin, de.seitenbau.serviceportal.prozesspipelin, with the an updated vcsUrl set to 'https://github.com/seitenbau'

### Expected Behavior
https://plugins.gradle.org/plugin/de.seitenbau.serviceportal.prozesspipeline displays:
**Source: https://github.com/seitenbau**

### Current Behavior
https://plugins.gradle.org/plugin/de.seitenbau.serviceportal.prozesspipeline still displays the URL published with previous versions of the plugin.

### Context
id("de.seitenbau.serviceportal.prozesspipeline") version "2024.01.10-0"
Version 2024.01.10-0 (latest)
Created 10 January 2024.

### Steps to Reproduce 
Publish a plugin with the vcsUrl set to https://some.old/url
Publish the next version of the same plugin with the vcsUrl set to https://some.NEW/url

### Your Environment
n/a

**Comment by ov7a** [comment] 2024-01-11 07:53
Sorry that you're having trouble with Gradle!

This is a duplicate of 
* https://github.com/gradle/plugin-portal-requests/issues/18

**Closed** 2024-01-11 07:53 UTC
Labels: a:bug
