### ISSUE TITLE
I've sussessful published a new plugin but I don't see plugin in my account page

### ISSUE THREAD

**Issue by cosic** [gradle/plugin-portal-requests#195] opened 2023-09-14 10:05 UTC
I've published a new Gradle Plugin and got message in terminal

```
* Task :plugin:publishPlugins
Thank you. Your new plugin ru.cian.rustore-publish-gradle-plugin has been submitted for approval by Gradle engineers. The request should be processed within the next few days, at which point you will be contacted via email.
```

And got email

>A new plugin version has been published.
>Group: ru.cian.rustore-plugin
>Plugin id: ru.cian.rustore-publish-gradle-plugin
>Version: 0.1.0
>If you have not published it, make sure to reset your publishing keys.
>
>You may delete the plugin within 7 days following its publication, afterward you can use https://github.com/gradle/plugin-portal->requests for issues/request or use plugin-portal-support@gradle.com for security sensitive things.
>
>Greetings,
>The Gradle Team
>https://gradle.org

but I don't see the plugin in my account page https://plugins.gradle.org/u/<ACCOUNT>

I've already have and published one another plugin before. For new plugin I've used the same credentials. 

### Expected Behavior
I see the plugin in my account page https://plugins.gradle.org/u/<ACCOUNT>

### Current Behavior
I don't see the plugin in my account page https://plugins.gradle.org/u/<ACCOUNT>
![2023-09-14_12-54-12](https://github.com/gradle/plugin-portal-requests/assets/2806586/2f443a9a-4017-4419-9b89-f0c847d4c612)

### Context
When I try to publish plugin again I got error

```
* What went wrong:
Execution failed for task ':plugin:publishPlugins'.
> Failed to post to server.
  Server responded with:
  Plugin: 'ru.cian.rustore-publish-gradle-plugin', version: '0.1.0' exists already. It was created: 2023-09-08 19:30:03.848
```

### Steps to Reproduce 
Just publish a new plugin

### Your Environment
* com.gradle.plugin-publish:1.2.1
* com.android.tools.build:gradle:7.4.2
* OpenJDK Runtime Environment Zulu19.32+13-CA

```
group = "ru.cian.rustore-plugin"
version = "0.1.0"

gradlePlugin {
    website = "https://github.com/cianru/rustore-publish-gradle-plugin"
    vcsUrl = "https://github.com/cianru/rustore-publish-gradle-plugin.git"
    plugins {
        rustorePlugin {
            id = "ru.cian.rustore-publish-gradle-plugin"
            displayName = "Rustore Publish Gradle Plugin"
            description = "A Gradle Plugin for publishing release built to Rustore"
            tags.set(["android", "rustore", "publishing", "deployment"])
            implementationClass = "ru.cian.rustore.publish.RustorePublishPlugin"
        }
    }
}
```

**Comment by ov7a** [comment] 2023-09-14 11:41
Sorry that you're having trouble with this!

Indeed this seems to be an issue on our side. I can see your plugin in our database.

I noticed that your vcsUrl is pointing to an empty Github repo. Could you please fix this according to our [guidelines](https://plugins.gradle.org/docs/publish-plugin#approval)?

It's unlikely that this issue was the root cause, but I think it should be fixed anyway before publishing.

**Comment by cosic** [comment] 2023-09-16 22:59
@ov7a Hi! Thank you for quick answer. I've upload code to repository by `vcsUrl` url. See https://github.com/cianru/rustore-publish-gradle-plugin

**Comment by ov7a** [comment] 2023-09-18 06:11
@cosic Thanks! I've approved the plugin, it should be available now.

**Closed by ov7a** 2023-09-18 06:11 UTC
Labels: a:bug
