### ISSUE TITLE
Support for user groups

### ISSUE THREAD

**Issue by sebersole** [gradle/plugin-portal-requests#56] opened 2020-08-07 17:48 UTC
Not sure how widely useful this would be, but for development teams (such as the Hibernate project) where more than one developer might work on plugins, it sure would be nice to simply have a group that real users could be added to.  

At the moment we are forced to create a "group user" and all members of the team need to know the API key for the group user associated with the plugins they wish to publish.  It gets worse when someone (such as myself) works on plugins for multiple groups - managing `~/.gradle/gradle.properties` to change the API key based on the group that particular plugin belongs to is simply difficult (if I even happen to remember)

### Expected Behavior

It would be very nice if instead a user could instead use there personal portal API key to publish these plugins.  This would mean a few changes I assume:

1) The ability to define a group
2) The ability to associate one-or-more users to a group
3) The ability to associate a plugin with a group rather than simply the user who happened to publish it.

### Current Behavior

Currently each group must define a distinct user representing the group.  An individual developer wishing to publish a group-owned plugin must (remember to) open `~/.gradle/gradle.properties` and change the API key entries for the plugin they plan to publish each time they wish to publish a plugin - which again is difficult when a developer develops / publishes plugins for multiple groups.

### Context

I develop multiple plugins.  Some of those are "personal plugins" - plugins I develop personally for various things.  Some are related to builds for the Hibernate project.  Some are related to builds for the Quarkus project.  Some are ...

Again, opening and changing my `~/.gradle/gradle.properties` every time I publish a plugin is just a real PITA

For example, see https://github.com/gradle/plugin-portal-requests/issues/55 and https://discuss.gradle.org/t/share-publishing-of-a-plugin-to-portal-with-users/35290/8

**Comment by Michael-Baylis** [comment] 2020-10-07 11:12
I would like the ability to have a group of users able to deploy the upcoming galasa.dev gradle plugins with their personal api keys.  At the moment I will have to create a shared api key,  but that doesn't leave an audit trail of how actually deployed the plugin.

**Comment by JLLeitschuh** [comment] 2020-10-07 20:10
This feature has been discussed, and it's something that we'd eventually like to add, but currently it's not on our roadmap.

**Comment by joschi** [comment] 2021-03-08 11:31
Would this effectively be the same as https://github.com/gradle/plugin-portal-requests/issues/16?

**Comment by donv** [comment] 2023-05-19 06:51
I would say this is a duplicate of #16 .

**Comment by ov7a** [comment] 2023-05-22 15:25
Thank you for your interest in Gradle Plugin Portal!

This issue will be closed as a duplicate of

* #16 

Please add your use case and 👍 to that issue.

**Closed by ov7a** 2023-05-22 15:25 UTC
Labels: a:feature
